---
- hosts: localhost
  become: yes
  roles:
    - rogerscuall.ansible-vsftpd

  vars_prompt:

  - name: test_user
    prompt: Enter username
    private: no

  - name: test_user_password
    prompt: Enter the password
    private: yes

  tasks:
  - name: add test user of the ftp
    tags: adduser
    command: /sbin/vsftpd-user add {{ test_user }} {{ test_user_password }} creates=/etc/vsftpd
