---
# tasks file for ansible-vsftpd
- name: install vsftpd
  apt: name={{ item }} state=latest cache_valid_time=3600 update_cache=yes
  with_items:
    - vsftpd
    - libpam-pwdfile

- name: create directory for user configuration
  command: file {{ vsftpd_user_config_dir }} state=directory

- name: create directory for key local_root from vsftpd.conf
  command: file {{ vsftpd_local_root }} state=directory owner=root group=owner

- name: copy file for PAM service
  template: src=vsftpd.pam.j2 dest=/etc/pam.d/vsftpd mode=644 backup=yes

- name: copy script the vsftpd-user
  template: src=vsftpd-user.j2 dest=/sbin/vsftpd-user mode=755

# will be create backup file if already exist
- name: copy config file of the vsftpd
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd.conf mode=644 backup=yes
  notify:
    - restart vsftpd
